### ISSUE TITLE
CI Pipeline and Build Shields

### ISSUE THREAD

**Issue by ubergarm** [tryshchenko/farvekonfigurator#1]
I recommend we move forward with https://github.com/auchenberg/volkswagen style shields to guarantee passing builds but am open to hardcoding it as well.

Cheers!

**Comment by tryshchenko** [comment]
Holy shit, it's amazing. We definitely need this!

Thanks!

**Comment by tryshchenko** [comment]
Added a build status widget from Volkswagen. However full integration is still the important plan.

**Comment by ubergarm** [comment]
Great, thanks so much for this wonderful improvement! Keep up the good work!
